baseURL = "http://example.org/"
languageCode = "en-us"
title = "My CV Website"
theme = "ananke"

[menu]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 3
